### ISSUE TITLE
when will this package be registered?

### ISSUE THREAD

**Issue by waynelapierre** [rcalxrc08/FinancialMonteCarlo.jl#1]
I found this package very interesting, when will it be registered?

**Comment by rcalxrc08** [comment]
Hi, still looking for a proper scope for the package. It was born as toy project, recently the scope has been extended a lot.
So far I there is no bound to the future developments, I am waiting for registering since the name 'FinancialMonteCarlo.jl' in the future could be not 100% appropriate.

I think I will merge this package with 'FinancialToolbox.jl' since the name seems way more appropriate.

**Comment by mkschulze** [comment]
I'm looking forward to using this for an educational and later maybe a production project out of that. Would be nice to see it registered.

**Comment by rcalxrc08** [comment]
[51630](https://github.com/JuliaRegistries/General/pull/51630)

**Comment by rcalxrc08** [comment]
Registered

**Comment by mkschulze** [comment]
awesome, thank you!
